projects:
  ionifits:
    schemaPath: src/graphql/schema.json
    includes:
      - src/graphql/**/*.graphql
    excludes:
      - amplify/**
    extensions:
      amplify:
        codeGenTarget: angular
        generatedFileName: src/app/API.service.ts
        docsFilePath: src/graphql
        graphQLApiId: drqhqq7pr5gsvlxmg4eo2upggq
      endpoints:
        prod: >-
          https://mdrhvj2e6zditmplzlsy6tcb5u.appsync-api.us-west-2.amazonaws.com/graphql
