// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile =  {
    "aws_project_region": "us-east-2",
    "aws_cognito_identity_pool_id": "us-east-2:c5371725-9b44-4297-a6a5-c6fb737a59c0",
    "aws_cognito_region": "us-east-2",
    "aws_user_pools_id": "us-east-2_iw70xoeVr",
    "aws_user_pools_web_client_id": "sr2oltr9oq1ruk3oaklniitai",
    "aws_dynamodb_all_tables_region": "us-east-2",
    "aws_dynamodb_table_schemas": [
        {
            "tableName": "person",
            "region": "us-east-2"
        }
    ]
};


export default awsmobile;
